/// Flutter icons IconGlobal
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconGlobal
///      fonts:
///       - asset: fonts/IconGlobal.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IconGlobal {
  IconGlobal._();

  static const _kFontFam = 'IconGlobal';
  static const String? _kFontPkg = null;

  static const IconData iconleave =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconworkinghrs =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconreportattendance =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconcheckin =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconcheckout =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconcheckin2 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconcheckout2 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icontouch =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoffice =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
